export const GET_MOVIES = 'GET_MOVIES';
export const GET_SERIES = 'GET_SERIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_SEARCH_VALUE = 'GET_SEARCH_VALUE';
export const GET_CHAR_VALUE = 'GET_CHAR_VALUE';
export const GET_MOVIE_GENRE = 'GET_MOVIE_GENRE';
export const GET_SERIES_GENRE = 'GET_SERIES_GENRE';
export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';